# This is a basic workflow to help you get started with Actions
name: Node.js CI
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main
  # branch
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at
        # https://nodejs.org/en/about/releases/
        node-version: [15.x]
    # Steps represent a sequence of tasks that will be executed as part of the
    # job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can
      # access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        # Use this to check for `cache-hit` ==> if:
        # steps.npm-cache.outputs.cache-hit != 'true'
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Some of the node versions (e.g. v12 & v14) don't install the latest
      # version of npm.
      - name: Update NPM
        run: npm install -g npm@7
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Format
        run: npm run format
      - name: Lint
        run: |
          npm link
          npm run lint
          npm run markdownlint
  release:
    needs: test
    # The if statement checks the github.ref context to determine the current
    # branch name; if the name is refs/heads/main, then the subsequent steps are
    # executed.
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Update to npm v7+
        run: npm install -g npm@latest
      - name: Prepare package for publish
        run: |
          npm ci
          npm run build
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
